<?xml version="1.0"?>
<!-- Source: https://kiranpalla.com/blog/ros-using-differential-drive-gazebo-plugin/ -->
<!-- Migrated to ROS2 with https://github.com/ros-simulation/gazebo_ros_pkgs/wiki/ROS-2-Migration%3A-Diff-drive -->

<robot xmlns:xacro="http://ros.org/wiki/xacro">
  <!--Gazebo Differential Drive Plugin-->
  <gazebo>
    <plugin name="differential_drive_controller" filename="libgazebo_ros_diff_drive.so">
      <!-- default namespace -->
      <ros>
        <!-- Set namespace -->
        <!-- <namespace></namespace> -->
        <!-- Remap default topics -->
        <!-- <argument>cmd_vel:=cmd_demo</argument> -->
        <!-- <argument>odom:=odom_demo</argument> -->
      </ros>

      <alwaysOn>true</alwaysOn>
      <!-- <update_rate>50</update_rate> -->
      <left_joint>left_wheel_joint</left_joint>
      <right_joint>right_wheel_joint</right_joint>
      <wheel_separation>${chassis_y+wheelwidth}</wheel_separation>
      <wheel_diameter>${wheeldiam}</wheel_diameter>
      <!-- Wheel acceleration, in rad/s^2, defaults to 0.0 rad/s^2 -->
      <!-- <max_wheel_acceleration>1.0</max_wheel_acceleration> -->
      <!-- Maximum torque which the wheels can produce, in Nm, defaults to 5 Nm -->
      <max_wheel_torque>20</max_wheel_torque>
      <odometry_frame>odom</odometry_frame>
      <robotBaseFrame>base_footprint</robotBaseFrame>
      
      <!-- Set to true to publish transforms for the odometry, defaults to true -->
      <publish_odom>true</publish_odom>
      <!-- Set to true to publish transforms for the wheel links, defaults to false -->
      <publish_wheel_tf>true</publish_wheel_tf>
      <publish_odom_tf>true</publish_odom_tf>

    </plugin>

      <!-- Use gazebo_ros_joint_state_publisher instead of publishWheelJointState -->
    <plugin name="joint_states" filename="libgazebo_ros_joint_state_publisher.so">
      <joint_name>right_wheel_joint</joint_name>
      <joint_name>left_wheel_joint</joint_name>
    </plugin>    
  </gazebo>
</robot>