<?xml version="1.0"?>
<!-- Source: https://kiranpalla.com/blog/ros-using-differential-drive-gazebo-plugin/ -->
<!-- Migrated to ROS2 with https://github.com/ros-simulation/gazebo_ros_pkgs/wiki/ROS-2-Migration%3A-Diff-drive -->
<!-- Further tutorials taken from the Nav2 Tutorials https://navigation.ros.org/setup_guides/index.html -->

<robot xmlns:xacro="http://ros.org/wiki/xacro">
  <!--Gazebo Differential Drive Plugin-->
  <gazebo>
    <!-- ++++++++++++++++++++++++++++++ Diff Drive Plugin ++++++++++++++++++++++++++++ -->
    <plugin name="$(arg prefix)_diff_drive" filename="libgazebo_ros_diff_drive.so">
      <!-- default namespace -->
      <ros>
        <remapping>/tf:=tf</remapping>
        <namespace>$(arg prefix)</namespace>
      </ros>

      <always_on>true</always_on>
      <update_rate>100</update_rate>
      <left_joint>$(arg prefix)_left_wheel_joint</left_joint>
      <right_joint>$(arg prefix)_right_wheel_joint</right_joint>
      <wheel_separation>${chassis_y+wheelwidth+2*wheelgap}</wheel_separation>
      <wheel_diameter>${wheeldiam}</wheel_diameter>
      <!-- Maximum torque which the wheels can produce, in Nm, defaults to 5 Nm -->
      <max_wheel_torque>20</max_wheel_torque>
      <!-- Wheel acceleration, in rad/s^2, defaults to 0.0 rad/s^2 -->
      <max_wheel_acceleration>1.0</max_wheel_acceleration>

      <odometry_frame>$(arg prefix)odom</odometry_frame>
      <robot_base_frame>$(arg prefix)_base_footprint</robot_base_frame>

      <!-- <odometry_topic>odom</odometry_topic> -->
      
      <!-- 0 is encoder, 1 is world (ground truth) -->
      <odometry_source>1</odometry_source>
      
      <publish_odom>true</publish_odom>
      <publish_odom_tf>true</publish_odom_tf>
      <publish_wheel_tf>true</publish_wheel_tf>

    </plugin>

    <!-- +++++++++++++++++++++++++++++ Joint State Plugin ++++++++++++++++++++++++++++ -->
    <plugin name="$(arg prefix)_joint_states" filename="libgazebo_ros_joint_state_publisher.so">
      <ros>
        <namespace>$(arg prefix)</namespace>
      </ros>
      <joint_name>$(arg prefix)_right_wheel_joint</joint_name>
      <joint_name>$(arg prefix)_left_wheel_joint</joint_name>
      <update_rate>100</update_rate>
    </plugin>


    <!-- Ground Truth plugins are not needed for now, 
      as the Diff Drive Plugin offers a ground truth transform... -->

    <!-- +++++++++++++++++++++ base_footprint Ground Truth Plugin ++++++++++++++++++++ -->
    <!-- <plugin name="$(arg prefix)_p3d_base_footprint" filename="libgazebo_ros_p3d.so">
      <ros>
        <namespace>$(arg prefix)</namespace>
        <remapping>odom:=$(arg prefix)_odom</remapping>
      </ros>
      <always_on>true</always_on>
      <update_rate>100</update_rate>
      <body_name>$(arg prefix)_base_footprint</body_name>
      <frame_name>world</frame_name>

      <gaussian_noise>0.00</gaussian_noise>
      <xyz_offset>0 0 0</xyz_offset>
      <rpy_offset>0 0 0</rpy_offset>
    </plugin> -->

    <!-- +++++++++++++++++++++++ right_wheel Ground Truth Plugin +++++++++++++++++++++ -->
    <!-- <plugin name="$(arg prefix)_p3d_right_wheel" filename="libgazebo_ros_p3d.so">
      <ros>
        <namespace>$(arg prefix)</namespace>
        <remapping>odom:=right_wheel_odom</remapping>
      </ros>
      <always_on>true</always_on>
      <update_rate>100</update_rate>
      <body_name>$(arg prefix)_right_wheel</body_name>
      <frame_name>world</frame_name>

      <gaussian_noise>0.00</gaussian_noise>
      <xyz_offset>0 0 0</xyz_offset>
      <rpy_offset>0 0 0</rpy_offset>
    </plugin> -->

    <!-- +++++++++++++++++++++++ left_wheel Ground Truth Plugin ++++++++++++++++++++++ -->
    <!-- <plugin name="$(arg prefix)_p3d_left_wheel" filename="libgazebo_ros_p3d.so">
      <ros>
        <namespace>$(arg prefix)</namespace>
        <remapping>odom:=left_wheel_odom</remapping>
      </ros>
      <always_on>true</always_on>
      <update_rate>100</update_rate>
      <body_name>$(arg prefix)_left_wheel</body_name>
      <frame_name>world</frame_name>

      <gaussian_noise>0.00</gaussian_noise>
      <xyz_offset>0 0 0</xyz_offset>
      <rpy_offset>0 0 0</rpy_offset>
    </plugin> -->
  </gazebo>

  <!-- ++++++++++++++++++++++++++++++++++ IMU Plugin +++++++++++++++++++++++++++++++++ -->
  <!-- <gazebo reference="$(arg prefix)_imu_link">
    <gravity>true</gravity>
    <sensor name="$(arg prefix)_imu_sensor" type="imu">
      <always_on>true</always_on>
      <update_rate>100</update_rate>
      <visualize>true</visualize>
      <topic>__default_topic__</topic>
      <plugin filename="libgazebo_ros_imu_sensor.so" name="$(arg prefix)_imu_plugin">
        <ros>
          Put namespace stuff here
          <namespace>$(arg prefix)</namespace>
          <remapping>~/out:=imu</remapping>
        </ros>
        <gaussianNoise>0.0</gaussianNoise>
        <xyzOffset>0 0 0</xyzOffset>
        <rpyOffset>0 0 0</rpyOffset>
        <frame_name>$(arg prefix)_imu_link</frame_name>
        <initial_orientation_as_reference>false</initial_orientation_as_reference>
      </plugin>
      <pose>0 0 0 0 0 0</pose>
      
      <imu>
        <angular_velocity>
          <x>
            <noise type="gaussian">
              <mean>0.0</mean>
              <stddev>2e-4</stddev>
              <bias_mean>0.0000075</bias_mean>
              <bias_stddev>0.0000008</bias_stddev>
            </noise>
          </x>
          <y>
            <noise type="gaussian">
              <mean>0.0</mean>
              <stddev>2e-4</stddev>
              <bias_mean>0.0000075</bias_mean>
              <bias_stddev>0.0000008</bias_stddev>
            </noise>
          </y>
          <z>
            <noise type="gaussian">
              <mean>0.0</mean>
              <stddev>2e-4</stddev>
              <bias_mean>0.0000075</bias_mean>
              <bias_stddev>0.0000008</bias_stddev>
            </noise>
          </z>
        </angular_velocity>
        <linear_acceleration>
          <x>
            <noise type="gaussian">
              <mean>0.0</mean>
              <stddev>1.7e-2</stddev>
              <bias_mean>0.1</bias_mean>
              <bias_stddev>0.001</bias_stddev>
            </noise>
          </x>
          <y>
            <noise type="gaussian">
              <mean>0.0</mean>
              <stddev>1.7e-2</stddev>
              <bias_mean>0.1</bias_mean>
              <bias_stddev>0.001</bias_stddev>
            </noise>
          </y>
          <z>
            <noise type="gaussian">
              <mean>0.0</mean>
              <stddev>1.7e-2</stddev>
              <bias_mean>0.1</bias_mean>
              <bias_stddev>0.001</bias_stddev>
            </noise>
          </z>
        </linear_acceleration>
      </imu>

    </sensor>
  </gazebo> -->
  
  <!-- +++++++++++++++++++++++++++++++++ Lidar Plugin ++++++++++++++++++++++++++++++++ -->
  <!-- <gazebo reference="$(arg prefix)_lidar_link">
    <sensor name="lidar" type="ray">
      <always_on>true</always_on>
      <visualize>true</visualize>
      <update_rate>5</update_rate>
      <ray>
        <scan>
          <horizontal>
            <samples>360</samples>
            <resolution>1.000000</resolution>
            <min_angle>0.000000</min_angle>
            <max_angle>6.280000</max_angle>
          </horizontal>
        </scan>
        <range>
          <min>0.120000</min>
          <max>3.5</max>
          <resolution>0.015000</resolution>
        </range>
        <noise>
          <type>gaussian</type>
          <mean>0.0</mean>
          <stddev>0.01</stddev>
        </noise>
      </ray>
      <plugin name="$(arg prefix)_scan" filename="libgazebo_ros_ray_sensor.so">
        <ros>
          <remapping>~/out:=scan</remapping>
          <namespace>$(arg prefix)</namespace>
        </ros>
        <output_type>sensor_msgs/LaserScan</output_type>
        <frame_name>$(arg prefix)_lidar_link</frame_name>
      </plugin>
    </sensor>
  </gazebo> -->

  <!-- ++++++++++++++++++++++++++++++++ Camera Plugin ++++++++++++++++++++++++++++++++ -->
  <!-- <gazebo reference="$(arg prefix)_camera_link">
    <sensor name="depth_camera" type="depth">
      <visualize>true</visualize>
      <update_rate>30.0</update_rate>
      <camera name="$(arg prefix)_camera">
        <horizontal_fov>1.047198</horizontal_fov>
        <image>
          <width>640</width>
          <height>480</height>
          <format>R8G8B8</format>
        </image>
        <clip>
          <near>0.05</near>
          <far>3</far>
        </clip>
      </camera>
      <plugin name="$(arg prefix)_depth_camera_controller" filename="libgazebo_ros_camera.so">
        <baseline>0.2</baseline>
        <alwaysOn>true</alwaysOn>
        <updateRate>0.0</updateRate>
        <frame_name>$(arg prefix)_camera_depth_frame</frame_name>
        <pointCloudCutoff>0.5</pointCloudCutoff>
        <pointCloudCutoffMax>3.0</pointCloudCutoffMax>
        <distortionK1>0</distortionK1>
        <distortionK2>0</distortionK2>
        <distortionK3>0</distortionK3>
        <distortionT1>0</distortionT1>
        <distortionT2>0</distortionT2>
        <CxPrime>0</CxPrime>
        <Cx>0</Cx>
        <Cy>0</Cy>
        <focalLength>0</focalLength>
        <hackBaseline>0</hackBaseline>
      </plugin>
    </sensor>
  </gazebo> -->

</robot>