<?xml version="1.0"?>
<robot name="robot_base" xmlns:xacro="http://ros.org/wiki/xacro">
  <xacro:arg name="prefix" default=""/>

  <!-- include robot params -->
  <xacro:include filename="materials.xacro"/>
  <xacro:include filename="dimensions.xacro"/>
  <xacro:include filename="inertia_properties.xacro"/>

  <!-- Base chassis box -->
  <link name="$(arg prefix)_base_footprint">
    <!-- <xacro:box_inertia m="0.1" w="0.001" h="0.001" d="0.001"/>
    <visual>
      <geometry> <box size="0.001 0.001 0.001" /> </geometry>
    </visual>
    <xacro:default_inertial mass="1"/> -->
  </link>

  <!-- ++++++++++++++++++++++++++++++++++ base link ++++++++++++++++++++++++++++++++++ -->
  <link name="$(arg prefix)_base_link">
    <xacro:box_inertia m="10.0" w="${chassis_x}" h="${chassis_y}" d="${chassis_z}"/>
    <visual>
      <geometry>
        <box size="${chassis_x} ${chassis_y} ${chassis_z}"/>
      </geometry>
      <material name="blue"/>
    </visual>
    <collision>
      <geometry>
        <box size="${chassis_x} ${chassis_y} ${chassis_z}"/>
      </geometry>
    </collision>
  </link>

  <joint name="$(arg prefix)_base_link_joint" type="fixed">
    <origin xyz="0 0 ${chassis_z/2+chassis_height}" rpy="0 0 0" />
    <!-- <parent link="base_footprint"/>
    <child link="base_link" /> -->
    <parent link="$(arg prefix)_base_footprint"/>
    <child link="$(arg prefix)_base_link" />
  </joint>

  <gazebo reference="$(arg prefix)_base_link">
    <material>Gazebo/Red</material>
  </gazebo>

  <!-- +++++++++++++++++++++++++++++++++++ Wheels ++++++++++++++++++++++++++++++++++++ -->
  <xacro:macro name="wheel" params="suffix reflect">
    <link name="$(arg prefix)_${suffix}_wheel">
      <visual>
        <origin xyz="0 0 0" rpy="${pi/2} 0 0" />
        <geometry>
          <cylinder radius="${wheeldiam/2}" length="${wheelwidth}"/>
        </geometry>
        <material name="black"/>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="${pi/2} 0 0" />
        <geometry>
          <cylinder radius="${wheeldiam/2}" length="${wheelwidth}"/>
        </geometry>
      </collision>
      <xacro:cylinder_inertia m="0.2" r="${wheeldiam/2}" h="${wheelwidth}"/>
    </link>

    <gazebo reference="$(arg prefix)_${suffix}_wheel">
      <material>Gazebo/Black</material>
    </gazebo>

    <joint name="$(arg prefix)_${suffix}_wheel_joint" type="continuous">
      <axis xyz="0 1 0" rpy="0 0 0" />
      <parent link="$(arg prefix)_base_link"/>
      <child link="$(arg prefix)_${suffix}_wheel"/>
      <!-- (y) Places the wheel such that it is on the outside of the chassis -->
      <!-- (z) Places the wheel such that chassis is `chassis_height` above the ground -->
      <origin xyz="0 ${((chassis_y+wheelwidth)/2 + wheelgap)*reflect} ${wheeldiam/2 - chassis_z/2 - chassis_height}" rpy="0 0 0"/>
    </joint>
  </xacro:macro>

  <!-- ++++++++++++++++++++++++++++++++ Caster wheels ++++++++++++++++++++++++++++++++ -->
  <xacro:macro name="caster" params="suffix reflect">
    <link name="$(arg prefix)_${suffix}_caster">
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <sphere radius="${chassis_height/2}"/>
        </geometry>
        <material name="black"/>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <sphere radius="${chassis_height/2}"/>
        </geometry>
      </collision>
      <xacro:sphere_inertia m="0.1" r="${chassis_height/2}"/>
      <!-- <xacro:box_inertia m="0.1" w="${chassis_height}" h="${chassis_height}" d="${chassis_height}"/> -->
    </link>
        
    <gazebo reference="$(arg prefix)_${suffix}_caster">
      <mu1>0.005</mu1>
      <mu2>0.005</mu2>
      <material>Gazebo/Black</material>
    </gazebo>

    <joint name="$(arg prefix)_${suffix}_caster_joint" type="fixed">
      <axis xyz="0 1 0" rpy="0 0 0" />
      <parent link="$(arg prefix)_base_link"/>
      <child link="$(arg prefix)_${suffix}_caster"/>
      <origin xyz="${(chassis_x-caster_edge_offset)*reflect/2} 0 ${-chassis_z/2 - chassis_height/2}" rpy="0 0 0"/>
    </joint>
  </xacro:macro>
  
  <!-- +++++++++++++++++++++++++++++ Instanstiate Macros +++++++++++++++++++++++++++++ -->
  <xacro:caster suffix="front" reflect="1"/>
  <xacro:caster suffix="rear" reflect="-1"/>
  <xacro:wheel suffix="left" reflect="1"/>
  <xacro:wheel suffix="right" reflect="-1"/>

  <!-- ++++++++++++++++++++ Additional sensors, not used for now +++++++++++++++++++++ -->
  <!-- IMU -->
  <!-- <link name="$(arg prefix)_imu_link">
    <visual>
      <geometry> <box size="0.1 0.1 0.1"/> </geometry>
    </visual>
    <collision>
      <geometry> <box size="0.1 0.1 0.1"/> </geometry>
    </collision>
    <xacro:box_inertia m="0.1" w="0.1" d="0.1" h="0.1"/>
  </link>

  <joint name="$(arg prefix)_imu_joint" type="fixed">
    <parent link="$(arg prefix)_base_link"/>
    <child link="$(arg prefix)_imu_link"/>
    <origin xyz="0 0 0.01"/>
  </joint> -->
  
  <!-- LIDAR -->
  <!-- <link name="$(arg prefix)_lidar_link">
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="0.125"/>
      <inertia ixx="0.001"  ixy="0"  ixz="0" iyy="0.001" iyz="0" izz="0.001" />
    </inertial>

    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <cylinder radius="0.0508" length="0.055"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <cylinder radius="0.0508" length="0.055"/>
      </geometry>
    </visual>
  </link>

  <joint name="$(arg prefix)_lidar_joint" type="fixed">
    <parent link="$(arg prefix)_base_link"/>
    <child link="$(arg prefix)_lidar_link"/>
    <origin xyz="0 0 ${chassis_z/2 + 0.055}" rpy="0 0 0"/>
  </joint> -->

  <!-- Depth Camera -->
  <!-- <link name="$(arg prefix)_camera_link">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="0.015 0.130 0.022"/>
      </geometry>
    </visual>
  
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="0.015 0.130 0.022"/>
      </geometry>
    </collision>
  
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="0.035"/>
      <inertia ixx="0.001"  ixy="0"  ixz="0" iyy="0.001" iyz="0" izz="0.001" />
    </inertial>
  </link>
  
  <joint name="$(arg prefix)_camera_joint" type="fixed">
    <parent link="$(arg prefix)_base_link"/>
    <child link="$(arg prefix)_camera_link"/>
    <origin xyz="${chassis_x/2 + 0.015} 0 0" rpy="0 0 0"/>
  </joint>
  
  <link name="$(arg prefix)_camera_depth_frame"/>
  <joint name="$(arg prefix)_camera_depth_joint" type="fixed">
    <origin xyz="0 0 0" rpy="${-pi/2} 0 ${-pi/2}"/>
    <parent link="$(arg prefix)_camera_link"/>
    <child link="$(arg prefix)_camera_depth_frame"/>
  </joint> -->

  <!-- Includes Differential Drive controller, IMU -->
  <xacro:include filename="gazebo_plugins.xacro"/>
</robot>