dwa_action_server:
  ros__parameters:
    robot_radius : 0.3
    safety_thresh : 0.5
    simulate_duration : 0.5
    action_duration : 0.05
    linear_speed_limit : 0.5
    angular_speed_limit : 1.0
    linear_step : 0.1
    angular_step : 0.1
    dist_thresh : 0.1
    dist_method : "L2"

/**:
  ros__parameters:
    pub_freq: 20.0  # Match action duration
    robot_list: ["robot1", "robot2", "robot3"]
    robot_starting_x: [0.0, 3.5, 0.0]
    robot_starting_y: [0.0, 0.0, 3.5]
    robot_starting_theta: []