/**:
  ros__parameters:
    pub_freq: 50.0  # Match action duration

    # Typically for the DWA Action Server
    robot_radius : 0.35
    safety_thresh : 0.3
    simulate_duration : 0.4
    action_duration : 0.03
    linear_speed_limit : 0.6
    angular_speed_limit : 1.5
    linear_step : 0.1
    angular_step : 0.2
    dist_thresh_hi : 0.2
    dist_thresh_lo : 0.05
    dist_method : "L2"
    inter_robot_dist : 3.0
    orientation_ub_deg : 180.0
    orientation_lb_deg : 20.0
    angular_K : 1.0 # the max proportion of dist_to_goal that angular contributes
    goal_K : 10.0
    obstacle_K: 1.0
    stall_det_period: 1.0
    stall_dist_thresh: 0.1
    replan_duration: 5.0  # How long to wait to replan when an obstacle is reached

    # Typically for the RRT Action Server
    rrt_path_bias: 0.1
    rrt_it_lim : 2000
    rrt_it_min : 50
    rrt_max_extend_length : 1.5
    rrt_connect_circle_dist : 1.5
    rrt_debug_plot : false
    waypoint_skip: true
    waypoint_replan: false
    # local_planner: 'dwa_action_server'
    # local_planner: 'dwa_multirobot_server'
    local_planner: 'dwa_replan_server'

    # Typically for odom_distribution node
    odom_dist_thresh: 2.0