dwa_action_server:
  ros__parameters:
    robot_radius : 0.7
    safety_thresh : 0.5
    simulate_duration : 0.25
    action_duration : 0.05
    linear_speed_limit : 0.5
    angular_speed_limit : 1.0
    linear_step : 0.1
    angular_step : 0.1
    dist_thresh : 0.1
    dist_method : "L2"
    inter_robot_dist : 3.0

/**:
  ros__parameters:
    pub_freq: 20.0  # Match action duration
    # robot_list: ["robot1", "robot2", "robot3"]
    # robot_starting_x: [-2.0, 0.0, 2.0]
    # robot_starting_y: [1.15, 1.15, 1.15]
    # robot_starting_theta: [0.0, 0.0, 0.0]
    robot_list: ["robot1"]
    robot_starting_x: [0.0]
    robot_starting_y: [1.15]
    robot_starting_theta: [0.0]