/**:
  ros__parameters:
    robot_list: ["robot1", "robot2", "robot3", "robot4", "robot5", "robot6",
                "robot7", "robot8", "robot9", "robot10", "robot11", "robot12"]
    robot_starting_x: []
    robot_starting_y: []
    robot_starting_theta: []
    total_goals: 10
    watchdog_timeout_s: 120
    result_folder: "result"
    params_filepath: "/home/tianyilim/fyp/ic-fyp/src/multirobot_control/params/planner_params.yaml"

    # If random goals are desired, leave this as an empty list
    goal_array: "[]"

    realtime_factor: 1.0