<?xml version="1.0" ?>
<sdf version="1.5">
<world name="factory_world_2" xmlns:xacro="http://www.ros.org/wiki/xacro">
  <!-- A global light source -->
  <include>
    <uri>model://sun</uri>
  </include>
  <!-- A ground plane -->
  <include>
    <uri>model://ground_plane</uri>
  </include>

  <!-- Default camera angle -->
  <gui fullscreen='0'>
    <camera name='user_camera'>
      <pose>0.0 0.0 19.5 0 1.57 1.57</pose>
      <view_controller>orbit</view_controller>
      <projection_type>perspective</projection_type>
    </camera>

    <grid>
      <cell_count>10</cell_count>
      <cell_size>1.0</cell_size>
    </grid>
  </gui>

  <xacro:property name="wall_h" value="2"/>
  <xacro:property name="wall_d" value="0.2"/>
  <!-- Dimension of shelves -->
  <xacro:property name="shelf_x" value="4"/>
  <xacro:property name="shelf_y" value="0.8"/>
  <!-- Spacing of shelves -->
  <xacro:property name="spacing_x" value="1.5"/>
  <xacro:property name="spacing_y" value="1.5"/>
  <!-- Number of shelves on X and Y -->
  <xacro:property name="num_shelves_x" value="3"/>
  <xacro:property name="num_shelves_y" value="5"/>
  <!-- Extent of bounding walls -->
  <xacro:property name="wall_x" value="${(num_shelves_x/2)*shelf_x + ((num_shelves_x+1)/2)*spacing_x}"/>
  <xacro:property name="wall_y" value="${(num_shelves_y/2)*shelf_y + ((num_shelves_y+1)/2)*spacing_y}"/>
  
  <xacro:include filename="elements/elements_cylinder.xacro" />
  <xacro:include filename="elements/elements_wall.xacro" />

  <!-- Loop through to create N links -->
  <xacro:macro name="shelf_gen" params="num total">

    <!-- Fixed in the X direction for now (if not need to have nested loops... -->
    <model name="aws_robomaker_warehouse_ShelfD_01_${num}_001">
      <include>
          <uri>model://aws_robomaker_warehouse_ShelfD_01</uri>
      </include>
      <pose frame="">-${shelf_x+spacing_x} ${(shelf_y+spacing_y)*(num-(total/2))} 0 0 0 0</pose>
    </model>  
  
    <model name="aws_robomaker_warehouse_ShelfE_01_${num}_001">
      <include>
          <uri>model://aws_robomaker_warehouse_ShelfE_01</uri>
      </include>
      <pose frame="">0 ${(shelf_y+spacing_y)*(num-(total/2))} 0 0 0 0</pose>
    </model>  
  
    <model name="aws_robomaker_warehouse_ShelfD_01_${num}_002">
      <include>
          <uri>model://aws_robomaker_warehouse_ShelfD_01</uri>
      </include>
      <pose frame="">${shelf_x+spacing_x} ${(shelf_y+spacing_y)*(num-(total/2))} 0 0 0 0</pose>
    </model>  

    <xacro:if value="${num}">
        <xacro:shelf_gen num="${num-1}" total="${total}" />
    </xacro:if>
  </xacro:macro>

  <xacro:shelf_gen num="${num_shelves_y-1}" total="${num_shelves_y-1}"/>
  
  <!-- Define walls for the simulation -->
  <xacro:wall_element num="1" w="${wall_d}" h="${wall_h}" d="${wall_y*2}" x="${wall_x+wall_d/2}" y="0"/>
  <xacro:wall_element num="2" w="${wall_d}" h="${wall_h}" d="${wall_y*2}" x="-${wall_x+wall_d/2}" y="0"/>
  <xacro:wall_element num="3" w="${wall_x*2}" h="${wall_h}" d="${wall_d}" x="0" y="${wall_y+wall_d/2}"/>
  <xacro:wall_element num="4" w="${wall_x*2}" h="${wall_h}" d="${wall_d}" x="0" y="-${wall_y+wall_d/2}"/>

</world>
</sdf>